name: test

on:
  push:
    branches:
      - master

jobs:
  build:

    name: my job
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]


    steps:
    - uses: actions/checkout@v2
    - name: Use OS in ${{ matrix.os }}
    - run: |
          cat /etc/os-release
          echo $HOSTNAME