name: test-linux-commands

on:
  push:
    branches:
      - main

jobs:
  run:

    name: my job
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]


    steps:
#    - uses: actions/checkout@v2
    - name: Use os in ${{ matrix.os }}
#      uses: actions/checkout@v2
      with: 
        os: ${{ matrix.os }}
      run: |
          cat /etc/os-release
          echo "HOSTNAME: $HOSTNAME"